# -*- coding: utf-8 -*-
"""2.2. Python Basics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JyR2_gGtwlt5Ej4wPwX3R1c8MZChhiG5

Programming Languages used for Machine Learning:


1.   Python
2.   R

#print function
"""

print("Machine Learning")

print("Machine Learning" + " Projects")

print(8)

print(8+3)

"""#Basic Data types:


1.   int
2.   float
3.   str




"""

type(8)

type(5.3)

type("english")

"""#Constants & Variables"""

marvel_super_hero = "Iron Man"
print(marvel_super_hero)

marvel_super_hero = "Captain America"
print(marvel_super_hero)

hero1 , hero2 , hero3 = "Iron Man" , "Captain America" , "Bat Man"
print(hero1)
print(hero2)
print(hero3)

x = y = z = 23
print(x)
print(y)
print(z)

"""# input Function"""

number_1 = int(input("Enter the first number : "))
number_2 = int(input("Enter the second number : "))

sum = number_1 + number_2
print(sum)

# changing the data type in python:
num = 5
print(float(num))