# -*- coding: utf-8 -*-
"""Basic Data Types in Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n8cQH3SWUw2hLdSyU_WEn4O0jBbPdVYx

Basic Data Types in Python:
1. Integer
2. Floating Point
3. Complex
4. Boolean
5. String
"""

# integers
a = 8
print(a)

type(a)

# floating point
b = 2.3
print(b)
type(b)

# complex numbers
c = 1 + 3j
print(c)
type(c)

"""Conversion of one data type to another"""

# int to float
x = 10
print(x)
type(x)

y = float(x)
print(y)
type(y)

# float to int
x = 5.88
print(x)
type(x)

y = int(x)
print(y)
type(y)

"""Boolean

1. True
2. False
"""

a = True
print(a)
type(a)

b = False
print(b)
type(b)

a = 7 < 3
print(a)
type(a)

a = 7 > 3
print(a)
type(a)

"""String"""

print("Machine Learning")

print('Machine Learning')

my_string = "Machine Learning"
print(my_string)
type(my_string)

print("Hello"*5)

"""Slicing"""

my_string = "Programming"

print(my_string[1:5])    # values from index 1 to 5-1 will be sliced

# step
print(my_string[0:10:2])

"""String Concatenation"""

word_1 = 'Machine '
word_2 = 'Learning'

print(word_1+word_2)