# -*- coding: utf-8 -*-
"""2.5. Operators in Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12qxLta7lNxRb_DOThlvXkninI9XUUGxJ

Operators in Python:
1. Arithmetic Operators
2. Assignment Operators
3. Comparison Operators
4. Logical Operators
5. Identity Operators
6. Membership Operators

1. Arithmetic Operators
"""

num_1 = 20
num_2 = 10

# addition
sum = num_1 + num_2
print('sum = ',sum)

# subtraction
diff = num_1 - num_2
print('difference = ',diff)

# multiplication
pro = num_1 * num_2
print('product = ',pro)

# division
quo = num_1 / num_2
print('quotient = ',quo)

# exponent
exp = num_1**num_2   # 20^10
print('exponent = ',exp)

# modulus
mod = num_1 % num_2
print('reminder = ',mod)

"""2. Assignment Operators

+=

-=

*=

**=

/=

%=
"""

a = 5
print(a)

a = 5
a += 5   # a = a + 5
print(a)

b = 5
b -= 2   # b = b-2
print(b)

"""3. Comparison Operators"""

a = 5
b = 10

print(a == b)   # equal to
print(a != b)   # not equal to
print(a > b)    # greater than
print(a < b)
print(a <= b)
print(a >= b)

"""4. Logical Operators

and

or

not
"""

a = 10

print( a>20 and a>5)
print( a>20 or a>5)
print( not( a>8 and a>5))

"""5. Identity Operator:

is 

is not
"""

x = 5
y = 5

print(x is y)

x = 5
y = 10

print(x is y)

x = 5
y = 5

print(x is not y)

x = 5
y = 10

print(x is not y)

"""6. Membership Operator:

in 

not in
"""

a = 5
b =10

c = [1,2,3,4,5]
print( a in c)
print( b in c)

a = 5
b =10

c = [1,2,3,4,5]
print( a not in c)
print( b not in c)

