# -*- coding: utf-8 -*-
"""2.6. if else statement in Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QDR486vxxwpN7PyRfmlpGyw51KkCOUJa

simple if else statement
"""

a = 30
b = 50

if (a>b):
  print('a is the greatest number')
else:
  print('b is the greatest number')

a = int(input('Enter the first number : '))
b = int(input('Enter the second number : '))

if (a>b):
  print('First number is the greatest')
else:
  print('Second number is the greatest')

"""if elif else statement"""

a = 15
b = 25
c = 30

if (b<a>c):
  print('a is the greatest number')
elif (a<b>c):
  print('b is the greatest number')
else:
  print('c is the greatest number')

"""nested if statement"""

a = 20
b = 40
c = 60

if (a>b):
  if (a>c):
    print('a is the greatest number')
  else:
    print('c is the greatest number')
else:
  if (b>c):
    print('b is the greatest number')
  else:
    print('c is the greatest number')

